
@baseUrl = http://localhost:3000

### Get All Expenses
GET {{baseUrl}}/expenses

### Add a Expense
POST {{baseUrl}}/expenses
content-type: application/json

{
    "id": "10",
    "date": "2028-01-16",
    "description": "Example expense #10 from Alice",
    "payer": "Alice",
    "amount": 100
}

### Remove all and add default expenses
POST {{baseUrl}}/expenses/reset
